export const USERS_FETCH_SUCCEEDED = 'USERS_FETCH_SUCCEEDED'
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED'
export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED'
export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'
